1.Import NumPy

In [1]:
import numpy as np
print("NumPy imported successfully")


NumPy imported successfully


2.Create NumPy Arrays

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Array a:")
print(a)

print("\nArray b:")
print(b)


Array a:
[1 2 3 4 5]

Array b:
[[10 20 30]
 [40 50 60]]


3.Shape, Dimension, Data Type

In [3]:
print("\nShape of a:", a.shape)
print("Shape of b:", b.shape)

print("\nDimensions of a:", a.ndim)
print("Dimensions of b:", b.ndim)

print("\nData type of a:", a.dtype)
print("Data type of b:", b.dtype)



Shape of a: (5,)
Shape of b: (2, 3)

Dimensions of a: 1
Dimensions of b: 2

Data type of a: int64
Data type of b: int64


4.Random Data Generation

In [4]:
rng = np.random.default_rng(42)

random_numbers = rng.integers(10, 100, size=10)

print("\nRandom Numbers:")
print(random_numbers)



Random Numbers:
[18 79 68 49 48 87 17 72 28 18]


5.Indexing & Slicing

In [5]:
print("\nFirst element of a:", a[0])
print("Last element of a:", a[-1])

print("\nFirst row of b:")
print(b[0])

print("\nFirst column of b:")
print(b[:, 0])



First element of a: 1
Last element of a: 5

First row of b:
[10 20 30]

First column of b:
[10 40]


6.Boolean Masking

In [6]:
filtered = random_numbers[random_numbers > 50]

print("\nNumbers greater than 50:")
print(filtered)
#Important


Numbers greater than 50:
[79 68 87 72]


7.Vectorized Operations

In [ ]:
print("\nArray a multiplied by 10:")
print(a * 10)

print("\nArray a plus 5:")
print(a + 5)
# No loops




Array a multiplied by 10:
[10 20 30 40 50]

Array a plus 5:
[ 6  7  8  9 10]


8.Broadcasting

In [8]:
broadcast_result = b + 100

print("\nBroadcasting example (b + 100):")
print(broadcast_result)



Broadcasting example (b + 100):
[[110 120 130]
 [140 150 160]]


9.Aggregations & Statistics

In [9]:
print("\nMean of a:", a.mean())
print("Sum of a:", a.sum())
print("Max of a:", a.max())
print("Index of max in a:", a.argmax())



Mean of a: 3.0
Sum of a: 15
Max of a: 5
Index of max in a: 4


10.Axis-based Aggregations

In [10]:
print("\nColumn-wise mean of b:")
print(b.mean(axis=0))

print("\nRow-wise mean of b:")
print(b.mean(axis=1))



Column-wise mean of b:
[25. 35. 45.]

Row-wise mean of b:
[20. 50.]


Linear Algebra Basics 

In [11]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5],
              [6]])

dot_product = A @ B

print("\nMatrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix multiplication (A @ B):")
print(dot_product)



Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5]
 [6]]

Matrix multiplication (A @ B):
[[17]
 [39]]
